package damas.entity;

/**
 * Movimientos generated by hbm2java
 */
public class Movimientos  implements java.io.Serializable {


     private Integer id;
     private Partidas partidas;
     private String movimientos;

    public Movimientos() {
    }

    public Movimientos(Partidas partidas, String movimientos) {
       this.partidas = partidas;
       this.movimientos = movimientos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Partidas getPartidas() {
        return this.partidas;
    }
    
    public void setPartidas(Partidas partidas) {
        this.partidas = partidas;
    }
    public String getMovimientos() {
        return this.movimientos;
    }
    
    public void setMovimientos(String movimientos) {
        this.movimientos = movimientos;
    }
}


