package damas.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Partidas generated by hbm2java
 */
public class Partidas  implements java.io.Serializable {


     private Integer id;
     private Date fecha;
     private String ganador;
     private int numMovimientos;
     private Set movimientoses = new HashSet(0);

    public Partidas() {
    }

	
    public Partidas(Date fecha, int numMovimientos) {
        this.fecha = fecha;
        this.numMovimientos = numMovimientos;
    }
    public Partidas(Date fecha, String ganador, int numMovimientos, Set movimientoses) {
       this.fecha = fecha;
       this.ganador = ganador;
       this.numMovimientos = numMovimientos;
       this.movimientoses = movimientoses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getGanador() {
        return this.ganador;
    }
    
    public void setGanador(String ganador) {
        this.ganador = ganador;
    }
    public int getNumMovimientos() {
        return this.numMovimientos;
    }
    
    public void setNumMovimientos(int numMovimientos) {
        this.numMovimientos = numMovimientos;
    }
    public Set getMovimientoses() {
        return this.movimientoses;
    }
    
    public void setMovimientoses(Set movimientoses) {
        this.movimientoses = movimientoses;
    }
}


